/**
 * HydroNourish — Supabase Database Type Definitions
 * Heritage Animal Clinic Capstone Project
 *
 * This file provides TypeScript types for the Supabase Database,
 * which enables full type inference when using the Supabase client.
 */

export interface Database {
  public: {
    Tables: {
      admin_profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          role: 'admin' | 'super_admin';
          department?: string | null;
          status: 'active' | 'inactive' | 'suspended';
          avatar_url: string | null;
          last_login_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          role?: 'admin' | 'super_admin';
          department?: string | null;
          status?: 'active' | 'inactive' | 'suspended';
          avatar_url?: string | null;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          role?: 'admin' | 'super_admin';
          department?: string | null;
          status?: 'active' | 'inactive' | 'suspended';
          avatar_url?: string | null;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      clinic_users: {
        Row: {
          id: string;
          name: string;
          full_name: string | null;
          email: string;
          role: string;
          department: string | null;
          status: string;
          last_active: string | null;
          avatar_url: string | null;
          is_protected: boolean;
          created_at?: string | null;
        };
        Insert: {
          id: string;
          name: string;
          full_name?: string | null;
          email: string;
          role: string;
          department?: string | null;
          status?: string;
          last_active?: string | null;
          avatar_url?: string | null;
          is_protected?: boolean;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          full_name?: string | null;
          email?: string;
          role?: string;
          department?: string | null;
          status?: string;
          last_active?: string | null;
          avatar_url?: string | null;
          is_protected?: boolean;
          created_at?: string | null;
        };
        Relationships: [];
      };
      pets: {
        Row: {
          id: string;
          name: string;
          species: string;
          breed: string;
          age: number;
          weight: number;
          sex: string | null;
          owner_name: string;
          owner_phone: string;
          owner_id: string | null;
          clinic_ref: string;
          assigned_device_id: string | null;
          health_status: string | null;
          avatar_url: string | null;
          portion_grams: number | null;
          times_per_day: number | null;
          food_type: string | null;
          hydration_target: number | null;
          latest_temp: number | null;
          latest_heart_rate: number | null;
          latest_activity: string | null;
          emergency_contact?: string | null;
          notes?: string | null;
          created_at: string | null;
        };
        Insert: {
          id: string;
          name: string;
          species: string;
          breed: string;
          age: number;
          weight: number;
          sex?: string | null;
          owner_name: string;
          owner_phone: string;
          owner_id?: string | null;
          clinic_ref: string;
          assigned_device_id?: string | null;
          health_status?: string | null;
          avatar_url?: string | null;
          portion_grams?: number | null;
          times_per_day?: number | null;
          food_type?: string | null;
          hydration_target?: number | null;
          latest_temp?: number | null;
          latest_heart_rate?: number | null;
          latest_activity?: string | null;
          emergency_contact?: string | null;
          notes?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          species?: string;
          breed?: string;
          age?: number;
          weight?: number;
          sex?: string | null;
          owner_name?: string;
          owner_phone?: string;
          owner_id?: string | null;
          clinic_ref?: string;
          assigned_device_id?: string | null;
          health_status?: string | null;
          avatar_url?: string | null;
          portion_grams?: number | null;
          times_per_day?: number | null;
          food_type?: string | null;
          hydration_target?: number | null;
          latest_temp?: number | null;
          latest_heart_rate?: number | null;
          latest_activity?: string | null;
          emergency_contact?: string | null;
          notes?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      pet_owners: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string;
          access_status: string;
          pet_ids: any;
          current_session_id: string | null;
          date_created: string;
          last_login: string | null;
          notes: string | null;
          password?: string | null;
          address?: string | null;
        };
        Insert: {
          id: string;
          name: string;
          email: string;
          phone: string;
          access_status?: string;
          pet_ids?: any;
          current_session_id?: string | null;
          date_created?: string;
          last_login?: string | null;
          notes?: string | null;
          password?: string | null;
          address?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          phone?: string;
          access_status?: string;
          pet_ids?: any;
          current_session_id?: string | null;
          date_created?: string;
          last_login?: string | null;
          notes?: string | null;
          password?: string | null;
          address?: string | null;
        };
        Relationships: [];
      };
      pet_sessions: {
        Row: {
          id: string;
          pet_id: string;
          pet_name: string;
          pet_species?: string | null;
          pet_breed?: string | null;
          pet_avatar_url?: string | null;
          owner_id: string | null;
          owner_name: string;
          owner_email?: string | null;
          device_id: string;
          admission_date: string;
          expected_release_date: string;
          actual_release_date: string | null;
          status: string;
          admission_notes: string | null;
          release_notes: string | null;
          emergency_contact: string | null;
          admission_admin: string;
          release_admin: string | null;
          release_condition: string | null;
          created_at?: string | null;
        };
        Insert: {
          id: string;
          pet_id: string;
          pet_name: string;
          pet_species?: string | null;
          pet_breed?: string | null;
          pet_avatar_url?: string | null;
          owner_id?: string | null;
          owner_name: string;
          owner_email?: string | null;
          device_id: string;
          admission_date: string;
          expected_release_date: string;
          actual_release_date?: string | null;
          status?: string;
          admission_notes?: string | null;
          release_notes?: string | null;
          emergency_contact?: string | null;
          admission_admin: string;
          release_admin?: string | null;
          release_condition?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          pet_id?: string;
          pet_name?: string;
          pet_species?: string | null;
          pet_breed?: string | null;
          pet_avatar_url?: string | null;
          owner_id?: string | null;
          owner_name?: string;
          owner_email?: string | null;
          device_id?: string;
          admission_date?: string;
          expected_release_date?: string;
          actual_release_date?: string | null;
          status?: string;
          admission_notes?: string | null;
          release_notes?: string | null;
          emergency_contact?: string | null;
          admission_admin?: string;
          release_admin?: string | null;
          release_condition?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      clinic_settings: {
        Row: {
          id: number;
          clinic_name: string;
          clinic_address: string;
          clinic_phone: string;
          license_id: string;
          default_portion_grams: number;
          default_hydration_ml_per_kg: number;
          temp_warning_min: number;
          temp_warning_max: number;
          hr_warning_min: number;
          hr_warning_max: number;
          email_notifications: boolean;
          sms_notifications: boolean;
          browser_notifications: boolean;
          theme: 'clinic-blue' | 'modern-emerald' | 'dark';
          compact_layout: boolean;
          api_endpoint: string;
          api_secret_key: string;
          webhook_url: string;
          updated_at?: string | null;
        };
        Insert: {
          id?: number;
          clinic_name?: string;
          clinic_address?: string;
          clinic_phone?: string;
          license_id?: string;
          default_portion_grams?: number;
          default_hydration_ml_per_kg?: number;
          temp_warning_min?: number;
          temp_warning_max?: number;
          hr_warning_min?: number;
          hr_warning_max?: number;
          email_notifications?: boolean;
          sms_notifications?: boolean;
          browser_notifications?: boolean;
          theme?: 'clinic-blue' | 'modern-emerald' | 'dark';
          compact_layout?: boolean;
          api_endpoint?: string;
          api_secret_key?: string;
          webhook_url?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: number;
          clinic_name?: string;
          clinic_address?: string;
          clinic_phone?: string;
          license_id?: string;
          default_portion_grams?: number;
          default_hydration_ml_per_kg?: number;
          temp_warning_min?: number;
          temp_warning_max?: number;
          hr_warning_min?: number;
          hr_warning_max?: number;
          email_notifications?: boolean;
          sms_notifications?: boolean;
          browser_notifications?: boolean;
          theme?: 'clinic-blue' | 'modern-emerald' | 'dark';
          compact_layout?: boolean;
          api_endpoint?: string;
          api_secret_key?: string;
          webhook_url?: string;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      devices: {
        Row: {
          id: string;
          device_name: string | null;
          assigned_pet_id: string | null;
          assigned_pet_name: string | null;
          status: string | null;
          hardware_status: string | null;
          wifi_signal_dbm: number | null;
          food_level_pct: number | null;
          water_level_pct: number | null;
          battery_pct: number | null;
          is_plugged_in: boolean | null;
          last_transmission: string | null;
          firmware_version: string | null;
          mac_address: string;
          created_at?: string | null;
        };
        Insert: {
          id: string;
          device_name?: string | null;
          assigned_pet_id?: string | null;
          assigned_pet_name?: string | null;
          status?: string | null;
          hardware_status?: string | null;
          wifi_signal_dbm?: number | null;
          food_level_pct?: number | null;
          water_level_pct?: number | null;
          battery_pct?: number | null;
          is_plugged_in?: boolean | null;
          last_transmission?: string | null;
          firmware_version?: string | null;
          mac_address: string;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          device_name?: string | null;
          assigned_pet_id?: string | null;
          assigned_pet_name?: string | null;
          status?: string | null;
          hardware_status?: string | null;
          wifi_signal_dbm?: number | null;
          food_level_pct?: number | null;
          water_level_pct?: number | null;
          battery_pct?: number | null;
          is_plugged_in?: boolean | null;
          last_transmission?: string | null;
          firmware_version?: string | null;
          mac_address?: string;
          created_at?: string | null;
        };
        Relationships: [];
      };
      feeding_schedules: {
        Row: {
          id: string;
          pet_id: string;
          pet_name: string;
          food_type: string | null;
          portion_grams: number;
          scheduled_time: string;
          dispense_status: string | null;
          device_id: string;
          last_dispensed_at: string | null;
          created_at?: string | null;
        };
        Insert: {
          id: string;
          pet_id: string;
          pet_name: string;
          food_type?: string | null;
          portion_grams: number;
          scheduled_time: string;
          dispense_status?: string | null;
          device_id: string;
          last_dispensed_at?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          pet_id?: string;
          pet_name?: string;
          food_type?: string | null;
          portion_grams?: number;
          scheduled_time?: string;
          dispense_status?: string | null;
          device_id?: string;
          last_dispensed_at?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      feeding_logs: {
        Row: {
          id: string;
          pet_id: string;
          pet_name: string;
          portion_grams: number;
          dispensed_at: string;
          status: string | null;
          device_id: string;
          session_id: string | null;
          created_at?: string | null;
        };
        Insert: {
          id: string;
          pet_id: string;
          pet_name: string;
          portion_grams: number;
          dispensed_at: string;
          status?: string | null;
          device_id: string;
          session_id?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          pet_id?: string;
          pet_name?: string;
          portion_grams?: number;
          dispensed_at?: string;
          status?: string | null;
          device_id?: string;
          session_id?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      hydration_logs: {
        Row: {
          id: string;
          pet_id: string;
          pet_name: string;
          amount_ml: number;
          timestamp: string;
          reservoir_level_pct: number | null;
          session_id: string | null;
          created_at?: string | null;
        };
        Insert: {
          id: string;
          pet_id: string;
          pet_name: string;
          amount_ml: number;
          timestamp: string;
          reservoir_level_pct?: number | null;
          session_id?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          pet_id?: string;
          pet_name?: string;
          amount_ml?: number;
          timestamp?: string;
          reservoir_level_pct?: number | null;
          session_id?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      vital_signs: {
        Row: {
          id: string;
          pet_id: string;
          pet_name: string;
          temperature: number;
          heart_rate: number;
          weight: number;
          activity_mins: number;
          status: string | null;
          timestamp: string;
          session_id: string | null;
          created_at?: string | null;
        };
        Insert: {
          id: string;
          pet_id: string;
          pet_name: string;
          temperature: number;
          heart_rate: number;
          weight: number;
          activity_mins: number;
          status?: string | null;
          timestamp: string;
          session_id?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          pet_id?: string;
          pet_name?: string;
          temperature?: number;
          heart_rate?: number;
          weight?: number;
          activity_mins?: number;
          status?: string | null;
          timestamp?: string;
          session_id?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      ai_alerts: {
        Row: {
          id: string;
          pet_id: string;
          pet_name: string;
          alert_type: string;
          observed_reading: string;
          severity: string;
          ai_observation: string;
          recommended_action: string;
          review_status: string | null;
          timestamp: string;
          created_at?: string | null;
        };
        Insert: {
          id: string;
          pet_id: string;
          pet_name: string;
          alert_type: string;
          observed_reading: string;
          severity: string;
          ai_observation: string;
          recommended_action: string;
          review_status?: string | null;
          timestamp: string;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          pet_id?: string;
          pet_name?: string;
          alert_type?: string;
          observed_reading?: string;
          severity?: string;
          ai_observation?: string;
          recommended_action?: string;
          review_status?: string | null;
          timestamp?: string;
          created_at?: string | null;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
